export const cssConstants = {
    colors: {
        white: '#ffffff',
        black: '#000000',
        darkGray: '#333333',
        paleGray: '#d0d0d0',
        veryLightGray: '#e0e0e0',
        lightGray: '#cccccc',
        indigo: '#3e50b5',
        pinkie: '#ff4081',
    },
    sizes: {
        full: '100%',
        max: '1500px',
        xxxl: '800px',
        xxl: '75%',
        xl: '600px',
        l: '120px',
        m: '60%',
        s: '20%',
        xxxs: '50px',
        xs: '10px',
        xxs: '2px',
    },
    font: {
        xxxl: '42px',
        xxl: '36px',
        xl: '32px',
        l: '28px',
        m: '24px',
        s: '18px',
        xs: '16px',
        xxs: '12px',
    },
    gaps: {
        l: '5%',
        m: '20px',
        s: '10px',
        xs: '5px',
    },
    margin: {
        l: '20px',
        m: '10px',
    },
    padding: {
        xxl: '20%',
        xl: '10%',
        l: '5%',
        m: '20px',
        s: '10px',
    },
    screenWidth: {
        wide: '2000px',
        small: '760px',
        mobile: '460px',
    },
}
